services:
  - type: web
    name: ortho-clinic
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FORM_SECRET
        sync: false
      - key: SEED_ADMIN_EMAIL
        value: valthguime@gmail.com
      - key: BACKEND_CORS_ORIGINS
        value: '["https://ortho-clinic-ldcd.onrender.com"]'
